<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PsTiger.Ast\PsTiger.Ast.csproj" />
    <ProjectReference Include="..\PsTiger.VirtualMachine\PsTiger.VirtualMachine.csproj" />
    <ProjectReference Include="..\PsTiger.Runtime\PsTiger.Runtime.csproj" />
  </ItemGroup>

</Project>