<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<IsTestProject>false</IsTestProject>

		<RootNamespace>Mlt.Tests.TestLibrary</RootNamespace>
		<AssemblyName>Mlt.Tests.TestLibrary</AssemblyName>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\VirtualMachine\VirtualMachine.csproj" />
	</ItemGroup>

</Project>